export default {
  login: 'jorgediazok',
  id: 47897689,
  node_id: 'MDQ6VXNlcjQ3ODk3Njg5',
  avatar_url: 'https://avatars0.githubusercontent.com/u/47897689?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jorgediazok',
  html_url: 'https://github.com/jorgediazok',
  followers_url: 'https://api.github.com/users/jorgediazok/followers',
  following_url:
    'https://api.github.com/users/jorgediazok/following{/other_user}',
  gists_url: 'https://api.github.com/users/jorgediazok/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/jorgediazok/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jorgediazok/subscriptions',
  organizations_url: 'https://api.github.com/users/jorgediazok/orgs',
  repos_url: 'https://api.github.com/users/jorgediazok/repos',
  events_url: 'https://api.github.com/users/jorgediazok/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/jorgediazok/received_events',
  type: 'User',
  site_admin: false,
  name: 'Jorge Díaz',
  company: null,
  blog: 'github.com/jorgediazok',
  location: 'Buenos Aires',
  email: null,
  hireable: true,
  bio: null,
  twitter_username: 'jdiazdiaz',
  public_repos: 81,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: '2019-02-22T16:58:18Z',
  updated_at: '2020-09-15T03:04:21Z',
};
